# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b39c0b31689f374cbb8480a8301cf6bd6d67f78366c1b65d29f6f0ac4b86346c3ba4fc9cd31b388f6ab3863008a5cb5cc5dea16fdb6d27a40fed7165e5fa23

test:
  secret_key_base: 1f715f9b4699cbc4325e1c7681237ba1aef97afca6d7c58465eeccc97cee12df8680df904681303560e2e39f850847bc32551b8bf487fff4d58f71965aadf728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
